name: Linux commands

on:
    push:

jobs:
    commands:
        runs-on: ubuntu-latest

        steps:
            - run: pwd

            - run: ls -la

            - run: date

            - run: whoami

